# Generated by Django 5.1.6 on 2025-05-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_members_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('serialno', models.IntegerField(default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adate', models.DateField(default='2023-10-01')),
                ('atime', models.CharField(default='00:00:00', max_length=20)),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
