# Generated by Django 5.1.6 on 2025-05-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='adate',
            field=models.DateField(),
        ),
    ]
